sonar.projectKey=Bayly-AI_BAI-1-NATION-MCP
sonar.organization=bayly-ai
sonar.projectName=BAI-1-NATION-MCP
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=tests/**,**/*.json,**/__pycache__/**,dist/**,contracts/**
