sonar.projectKey=Bayly-AI_HATH0R-MCP
sonar.organization=bayly-ai
sonar.projectName=HATH0R-MCP
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=tests/**,**/*.json,**/__pycache__/**,dist/**,contracts/**
